apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:           
  name: auth-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: auth
spec:
  ingressClassName: nginx
  rules:
#  - host: auth-service.hw16-in-helm.svc.cluster.local
  - host: arch.homework
    http:
      paths:
      - pathType: Prefix
        path: "/auth"
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - pathType: Prefix
        path: "/auth2"
        backend:
          service:
            name: auth-service
            port:
              number: 80





